---
name: docker-build

on:
  push:
    branches-ignore:
    - 'development/**'

env:
  REGISTRY_NAME: registry.scality.com
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildk
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_NAME }}/${{ env.PROJECT_NAME }}-dev/${{ env.PROJECT_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push dashboards to the development namespace
        run: |
          oras push ${{ env.REGISTRY_NAME }}/${{ env.PROJECT_NAME }}-dev/${{ env.PROJECT_NAME }}-dashboards:${{ github.sha }} \
          ingestion/ingestion-processor-dashboard.json:application/grafana-dashboard+json \
          ingestion/ingestion-producer-dashboard.json:application/grafana-dashboard+json \
          ingestion/ingestion-global-dashboard.json:application/grafana-dashboard+json
        working-directory: monitoring
